version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: banco-postgres
    environment:
      POSTGRES_DB: bancodb
      POSTGRES_USER: banco_user
      POSTGRES_PASSWORD: banco_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U banco_user -d bancodb" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - banco-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: banco-backend
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/bancodb
      DB_USERNAME: banco_user
      DB_PASSWORD: banco_pass
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - banco-network
    restart: on-failure

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: banco-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - banco-network

volumes:
  postgres_data:


networks:
  banco-network:
    driver: bridge
